### PR TITLE
Update gitignore.

### PR DESCRIPTION
**Pull request by alunduil**
Add .direnv to ignores and update the Haskell section from gitignore.io.

### CODE REVIEW

**Review by swarren83 — COMMENTED** [review]
Do you typically lump version bumps into other commits?  Should the version bump of alpine and cabal be it's own commit or PR?  Or does the rewrite of your travis config test that the new versions work?

**Comment by alunduil** [comment]
I don't typically and am holding off on a bump of hakyll.  What you're calling version bumps are test and build details that have been neglected for too long and need an update so they even work.  Without these changes the tests fail.  I could split them out but they're going to block this regardless so I just lumped them together.

**Comment by alunduil** [comment]
I don't see a bump of cabal in this pull request either, do you mean the change in which GHC is used for building to match my and alpine's systems?

**Comment by alunduil** [comment]
@swarren83 why did you post a review of you weren't requesting changes, commenting on a particular line, or approving?  Do you approve of this change?

**Review by swarren83 — APPROVED** [review]
LGTM

**Comment by swarren83** [comment]
@alunduil I used the `comment` option of the review because I did not want to request changes and was not sure I was ready to approve.  I have just been busy lately and unable to get back to this in a timely manner.

**Pull request merged**
